import PageShell from "../../components/PageShell";
import AdSlot from "../../components/AdSlot";
import { FileText } from "lucide-react";

export const metadata = {
  title: "Terms of Service — AI Detector Pro",
  description:
    "Terms of service for AI Detector Pro. Heuristic estimates only; no warranty of accuracy.",
};

export default function TermsPage() {
  return (
    <PageShell>
      <div className="flex items-center gap-3">
        <span className="grid h-11 w-11 place-items-center rounded-xl bg-gradient-to-br from-blue-500 to-purple-600">
          <FileText className="h-6 w-6 text-white" />
        </span>
        <h1 className="font-display text-3xl font-bold sm:text-4xl">
          Terms of Service
        </h1>
      </div>
      <p className="mt-4 text-sm text-slate-400">
        Last updated: August 29, 2026
      </p>

      <Block title="1. Acceptance of Terms">
        <p className="mt-3 text-sm leading-relaxed text-slate-300">
          By accessing or using AI Detector Pro (&quot;the Service&quot;), you
          agree to be bound by these Terms of Service. If you do not agree,
          please discontinue use of the Service.
        </p>
      </Block>

      <Block title="2. Description of Service">
        <p className="mt-3 text-sm leading-relaxed text-slate-300">
          AI Detector Pro is a free, browser-based tool that estimates the
          likelihood that a given text was generated by an AI model. Analysis
          is performed locally in your browser using statistical heuristics.
          No text is transmitted to or stored on any server.
        </p>
      </Block>

      <Block title="3. No Warranty &amp; Accuracy Disclaimer">
        <p className="mt-3 text-sm leading-relaxed text-slate-300">
          The Service is provided &quot;as is&quot; and &quot;as
          available&quot; without warranties of any kind, express or implied.
          AI detection scores are <strong className="text-white">heuristic
          estimates</strong> and are not guaranteed to be accurate. The Service
          cannot definitively prove that any text was written by a human or by
          AI. You are solely responsible for how you interpret and act on the
          results.
        </p>
        <div className="mt-4 rounded-xl border border-amber-500/30 bg-amber-500/10 p-3 text-xs text-amber-200">
          Do not use AI Detector Pro as the sole basis for academic,
          disciplinary, employment, or legal decisions.
        </div>
      </Block>

      <Block title="4. Acceptable Use">
        <ul className="mt-3 space-y-2 text-sm text-slate-300">
          <li>• You may use the Service for personal, educational, and commercial research purposes.</li>
          <li>• You may not use the Service to harass, defame, or falsely accuse individuals of misconduct.</li>
          <li>• You may not attempt to reverse-engineer, overload, or disrupt the Service.</li>
          <li>• You are responsible for ensuring you have the right to analyze any text you submit.</li>
        </ul>
      </Block>

      <Block title="5. Intellectual Property">
        <p className="mt-3 text-sm leading-relaxed text-slate-300">
          The Service&apos;s design, branding, and source code are protected by
          applicable intellectual property laws. The text you submit remains
          yours; we claim no ownership over it and, per our Privacy Policy,
          never store it.
        </p>
      </Block>

      <Block title="6. Limitation of Liability">
        <p className="mt-3 text-sm leading-relaxed text-slate-300">
          To the maximum extent permitted by law, AI Detector Pro and its
          operators shall not be liable for any indirect, incidental, special,
          consequential, or punitive damages arising from your use of, or
          reliance on, the Service — including any decision made on the basis
          of an AI probability score.
        </p>
      </Block>

      <Block title="7. Third-Party Advertising">
        <p className="mt-3 text-sm leading-relaxed text-slate-300">
          The Service may display ads served by third parties such as Google
          AdSense. These parties may use cookies (including the DART cookie) as
          described in our Privacy Policy. We are not responsible for the
          content of third-party advertisements.
        </p>
      </Block>

      <Block title="8. Changes to These Terms">
        <p className="mt-3 text-sm leading-relaxed text-slate-300">
          We may revise these Terms at any time. Continued use after changes
          are posted constitutes acceptance of the revised Terms.
        </p>
      </Block>

      <Block title="9. Contact">
        <p className="mt-3 text-sm leading-relaxed text-slate-300">
          Questions about these Terms? Email{" "}
          <a
            className="text-blue-400 underline underline-offset-2"
            href="mailto:support@aidetectorpro.app"
          >
            support@aidetectorpro.app
          </a>
          .
        </p>
      </Block>

      <div className="mt-8">
        <AdSlot format="leaderboard" slot="terms" />
      </div>
    </PageShell>
  );
}

function Block({ title, children }) {
  return (
    <div className="glass-card mt-6 p-6 sm:p-8">
      <h2 className="font-display text-xl font-bold text-white">{title}</h2>
      {children}
    </div>
  );
}
